-- CREATE TABLE IF NOT EXISTS student(
--     id SERIAL PRIMARY KEY,
--     name VARCHAR(20) NOT NULL,
--     email VARCHAR(100) NOT NULL UNIQUE,
--     dob DATE,
--     phone INTEGER NOT NULL UNIQUE,
--     marks REAL CHECK(marks>-1 AND marks<100),
--     is_married BOOLEAN NOT NULL DEFAULT FALSE,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );


--ALTER TABLE student ADD COLUMN age INTEGER;
--ALTER TABLE student ADD COLUMN pocket_money INTEGER;
-- ALTER TABLE student ADD COLUMN car TEXT DEFAULT 'BMW';

--ALTER TABLE student DROP COLUMN is_married;
ALTER TABLE student
ALTER COLUMN dob TYPE TEXT
USING dob::TEXT;

